add_newline = false

[character]
#symbol = "ìˆ€"
#use_symbol_for_status = true

[line_break]
disabled = true

[java]
symbol = "î˜› "
disabled = true


[git_branch]
style = "yellow"

[git_status]
stashed.value = ""
modified = "ğš«"
style = "red"

[cmd_duration]
style = "red"
